name: Pull request

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - dev
    paths-ignore:
#      - ".github/**"
      - "*.md"

jobs:
  belt_conveyor:
    name: Belt
    uses: ./.github/workflows/sub_belt.yml
    with:
      # intermediary registry in which architecture-specific images must be pushed
      DOCKER_BUILD_REPO: "nwodtuhs/exegol-builds"
      # final registry target, in which arch-specific images must be aggregated
      DOCKER_TARGET_REPO: "nwodtuhs/exegol-dev"
      IMAGE_BASE_NAME: "PR"
      DOCKERFILE: "Dockerfile"
      SUPPORTED_ARCH: '["amd64","arm64"]'
      PR_MODE: true