name: Release (ad)

on:
  push:
    tags:
      - '*'
    paths-ignore:
      - ".github/**"
      - "*.md"

jobs:
  belt_conveyor:
    name: Belt
    needs: pre_belt
    uses: ./.github/workflows/sub_belt.yml
    with:
      # intermediary registry in which architecture-specific images must be pushed
      DOCKER_BUILD_REPO: "nwodtuhs/exegol-builds"
      # final registry target, in which arch-specific images must be aggregated
      DOCKER_TARGET_REPO: "nwodtuhs/exegol-dev"
      IMAGE_BASE_NAME: "ad"
      DOCKERFILE: "ad.dockerfile"
      # Setting IMAGE_VERSION for prod images != nightly
      IMAGE_VERSION: ${{ github.ref_name }}
      SUPPORTED_ARCH: '["amd64","arm64"]'
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
