name: ad build

on:
  push:
    tags:
      - '*'

jobs:
  buildx:
    timeout-minutes: 2880
    runs-on: self-hosted
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare build
        id: prepare_build
        run: |
          IMAGE_NAME="ad"
          DOCKER_REPO=nwodtuhs/exegol-dev
          IMAGE_VERSION=${GITHUB_REF/refs\/tags\//}
          IMAGE_TAGS="${DOCKER_REPO}:${IMAGE_NAME},${DOCKER_REPO}:${IMAGE_NAME}-${IMAGE_VERSION}"
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo ::set-output name=image_repo::${DOCKER_REPO}
          echo ::set-output name=image_tags::${IMAGE_TAGS}
          echo ::set-output name=image_name::${IMAGE_NAME}
          echo ::set-output name=image_version::${IMAGE_VERSION}
          echo ::set-output name=build_date::${BUILD_DATE}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Dockerhub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push the image
        if: success()
        uses: docker/build-push-action@v3
        with:
          outputs: type=image,push=true
          build-args: |
            TAG=${{ steps.prepare_build.outputs.image_name }}
            VERSION=${{ steps.prepare_build.outputs.image_version }}
            BUILD_DATE=${{ steps.prepare_build.outputs.build_date }}
          tags: ${{ steps.prepare_build.outputs.image_tags }}
          platforms: linux/amd64,linux/arm64
          file: ./ad.dockerfile
          context: .