name: debug build

on:
  push:
    branches:
      - dev

jobs:
  arm64_buildx:
    timeout-minutes: 360
    runs-on: [self-hosted, arm64]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare build
        id: prepare_build
        run: |
          IMAGE_NAME="nightly"
          DOCKER_REPO=nwodtuhs/exegol-builds
          COMMIT_ID=$(git rev-parse "$GITHUB_SHA")
          IMAGE_VERSION=${COMMIT_ID:0:8}
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "image_repo=${DOCKER_REPO}" >> $GITHUB_OUTPUT
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "image_version=${IMAGE_VERSION}" >> $GITHUB_OUTPUT
          echo "build_date=${BUILD_DATE}" >> $GITHUB_OUTPUT
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Dockerhub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push the image
        if: success()
        uses: docker/build-push-action@v3
        with:
          outputs: type=image,push=true
          build-args: |
            TAG=${{ steps.prepare_build.outputs.image_name }}
            VERSION=${{ steps.prepare_build.outputs.image_version }}
            BUILD_DATE=${{ steps.prepare_build.outputs.build_date }}
          tags: ${{ steps.prepare_build.outputs.image_repo }}:${{ steps.prepare_build.outputs.image_name }}
          platforms: linux/arm64
          file: ./debug.dockerfile
          context: .
  amd64_buildx:
    timeout-minutes: 360
    runs-on: [self-hosted, amd64]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare build
        id: prepare_build
        run: |
          IMAGE_NAME="nightly"
          DOCKER_REPO=nwodtuhs/exegol-builds
          COMMIT_ID=$(git rev-parse "$GITHUB_SHA")
          IMAGE_VERSION=${COMMIT_ID:0:8}
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "image_repo=${DOCKER_REPO}" >> $GITHUB_OUTPUT
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "image_version=${IMAGE_VERSION}" >> $GITHUB_OUTPUT
          echo "build_date=${BUILD_DATE}" >> $GITHUB_OUTPUT
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Dockerhub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push the image
        if: success()
        uses: docker/build-push-action@v3
        with:
          outputs: type=image,push=true
          build-args: |
            TAG=${{ steps.prepare_build.outputs.image_name }}
            VERSION=${{ steps.prepare_build.outputs.image_version }}
            BUILD_DATE=${{ steps.prepare_build.outputs.build_date }}
          tags: ${{ steps.prepare_build.outputs.image_repo }}:${{ steps.prepare_build.outputs.image_name }}
          platforms: linux/amd64
          file: ./debug.dockerfile
          context: .
  manifest_build:
    timeout-minutes: 60
    needs: [ arm64_buildx, amd64_buildx ]
    runs-on: self-hosted
    steps:
      - name: Login to Dockerhub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Create manifest
        if: success()
        run: |
          docker manifest create nwodtuhs/exegol-dev:debug nwodtuhs/exegol-builds:debug-arm64 nwodtuhs/exegol-builds:debug-amd64
      -
        name: Push manifest
        if: success()
        run: |
          docker manifest push nwodtuhs/exegol-dev:debug
      -
        name: Remove intermediate images
        if: success()
        run: |
          HUB_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{'username': \"${{ secrets.DOCKER_USERNAME }}\", 'password': \"${{ secrets.DOCKER_PASSWORD }}\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
          curl -i -X DELETE -H "Accept: application/json" -H "Authorization: JWT $HUB_TOKEN" https://hub.docker.com/v2/repositories/nwodtuhs/exegol-builds/tags/debug-arm64/
          curl -i -X DELETE -H "Accept: application/json" -H "Authorization: JWT $HUB_TOKEN" https://hub.docker.com/v2/repositories/nwodtuhs/exegol-builds/tags/debug-amd64/
