name: debug build

on:
  push:
    branches: dev

jobs:
  buildx:
    timeout-minutes: 2880
    runs-on: self-hosted
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare build
        id: prepare_build
        run: |
          IMAGE_NAME="debug"
          DOCKER_REPO=nwodtuhs/exegol-dev
          COMMIT_ID=$(git rev-parse "$GITHUB_SHA")
          IMAGE_VERSION=${COMMIT_ID:0:8}
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "image_repo=${DOCKER_REPO}" >> $GITHUB_OUTPUT
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "image_version=${IMAGE_VERSION}" >> $GITHUB_OUTPUT
          echo "build_date=${BUILD_DATE}" >> $GITHUB_OUTPUT
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Dockerhub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push the image
        if: success()
        uses: docker/build-push-action@v3
        with:
          outputs: type=image,push=true
          build-args: |
            TAG=${{ steps.prepare_build.outputs.image_name }}
            VERSION=${{ steps.prepare_build.outputs.image_version }}
            BUILD_DATE=${{ steps.prepare_build.outputs.build_date }}
          tags: ${{ steps.prepare_build.outputs.image_repo }}:${{ steps.prepare_build.outputs.image_name }}
          platforms: linux/arm/v7
          file: ./debug_all.dockerfile
          context: .