name: Release (all tags)

on:
  push:
    tags:
      - "*.*.*"
      - "*.*.*b*"

env:
  # intermediary registry in which architecture-specific images must be pushed
  # todo : change this to preprod, and the var name to DOCKER_PREPROD_REPO
  DOCKER_BUILD_REPO: "nwodtuhs/exegol-dev-preprod"
  # final registry target, in which arch-specific images must be aggregated
  DOCKER_TARGET_REPO: "nwodtuhs/exegol-dev-prod"
  # Setting IMAGE_VERSION for prod images != nightly
  IMAGE_VERSION: ${{ github.ref_name }}



jobs:
  inspect:
    name: Publish manifests
    strategy:
      matrix:
        tag: [ debug_release ]
    #        tag: [ full, light, ad, web, osint ]
    uses: ./.github/workflows/sub_manifest.yml
    with:
      PREPROD_MANIFEST_LIST: ${DOCKER_BUILD_REPO}:${{ matrix.tag }}
      PROD_MANIFEST_LIST: ${DOCKER_TARGET_REPO}:${{ matrix.tag }}
  inspect_version:
    name: Publish version manifests
    strategy:
      matrix:
        tag: [ debug_release ]
    #        tag: [ full, light, ad, web, osint ]
    uses: ./.github/workflows/sub_manifest.yml
    with:
      PREPROD_MANIFEST_LIST: ${DOCKER_BUILD_REPO}:${{ matrix.tag }}-${{ env.IMAGE_VERSION }}
      PROD_MANIFEST_LIST: ${DOCKER_TARGET_REPO}:${{ matrix.tag }}-${{ env.IMAGE_VERSION }}