name: Pull request

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - dev
    paths-ignore:
#      - ".github/**"
      - "*.md"

env:
  # intermediary registry in which architecture-specific images must be pushed
  DOCKER_BUILD_REPO: "nwodtuhs/exegol-builds"
  # final registry target, in which arch-specific images must be aggregated
  DOCKER_TARGET_REPO: "nwodtuhs/exegol-dev-prod"
  DOCKERFILE: "debug.dockerfile"

jobs:
  varset:
    name: Initialize variables
    runs-on: self-hosted
    outputs:
      DOCKER_BUILD_REPO: ${{ steps.varset.outputs.DOCKER_BUILD_REPO }}
      DOCKER_TARGET_REPO: ${{ steps.varset.outputs.DOCKER_TARGET_REPO }}
      IMAGE_BASE_NAME: ${{ steps.varset.outputs.IMAGE_BASE_NAME }}
      DOCKERFILE: ${{ steps.varset.outputs.DOCKERFILE }}
      #IMAGE_VERSION: ${{ steps.varset.outputs.IMAGE_VERSION }}
    steps:
      - name: Passing workflow env vars to reusable workflows
        id: varset
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "DOCKER_BUILD_REPO=${DOCKER_BUILD_REPO}" >> $GITHUB_OUTPUT
          echo "DOCKER_TARGET_REPO=${DOCKER_TARGET_REPO}" >> $GITHUB_OUTPUT
          echo "IMAGE_BASE_NAME=PR${PR_NUMBER}"
          echo "IMAGE_BASE_NAME=PR${PR_NUMBER}" >> $GITHUB_OUTPUT
          echo "DOCKERFILE=${DOCKERFILE}" >> $GITHUB_OUTPUT

  build_belt:
    name: Build belt
    needs: varset
    strategy:
      fail-fast: false
      matrix:
        arch: [ arm64, amd64 ]
    uses: ./.github/workflows/sub_build_belt.yml
    with:
      DOCKER_BUILD_REPO: ${{ needs.varset.outputs.DOCKER_BUILD_REPO }}
      DOCKER_TARGET_REPO: ${{ needs.varset.outputs.DOCKER_TARGET_REPO }}
      IMAGE_BASE_NAME: ${{ needs.varset.outputs.IMAGE_BASE_NAME }}
      DOCKERFILE: ${{ needs.varset.outputs.DOCKERFILE }}
      IMAGE_VERSION: ${{ needs.varset.outputs.IMAGE_VERSION }}
      ARCH: ${{ matrix.arch }}
      PR_MODE: true
