name: Release (all tags)

on:
  push:
    tags:
      - "*.*.*"
      - "*.*.*b*"

env:
  # intermediary registry in which architecture-specific images must be pushed
  # todo : change this to preprod, and the var name to DOCKER_PREPROD_REPO
  DOCKER_BUILD_REPO: "nwodtuhs/exegol-dev-preprod"
  # final registry target, in which arch-specific images must be aggregated
  DOCKER_TARGET_REPO: "nwodtuhs/exegol-dev-prod"
  # Setting IMAGE_VERSION for prod images != nightly
  IMAGE_VERSION: ${{ github.ref_name }}

jobs:
  publish:
    name: Push to prod
    timeout-minutes: 60
    runs-on: self-hosted
    strategy:
      matrix:
        tag: [ debug_release ]
#        tag: [ full, light, ad, web, osint ]
    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create and push version manifest
        if: success() && env.IMAGE_VERSION != ''
        run: |
          echo "Create version manifest"
          docker manifest create ${DOCKER_TARGET_REPO}:${{ matrix.tag }}-${IMAGE_VERSION} ${DOCKER_BUILD_REPO}:${{ matrix.tag }}
          docker manifest push ${DOCKER_TARGET_REPO}:${{ matrix.tag }}-${IMAGE_VERSION}
          docker manifest rm ${DOCKER_TARGET_REPO}:${{ matrix.tag }}-${IMAGE_VERSION}