name: DEBUG

# entrypoint to an image. This workflow defines the list of architetures and calls sub_belt for

on:
  push:
#    branches:
#      - main
    paths-ignore:
#      - ".github/**"
      - "*.md"
jobs:
  belt_conveyor:
    name: Belt
    uses: ./.github/workflows/sub_belt.yml
    with:
      # intermediary registry in which architecture-specific images must be pushed
      DOCKER_BUILD_REPO: "nwodtuhs/exegol-builds"
      # final registry target, in which arch-specific images must be aggregated
      DOCKER_TARGET_REPO: "nwodtuhs/exegol-dev"
      IMAGE_BASE_NAME: "debug"
      DOCKERFILE: "debug.dockerfile"
      # Setting IMAGE_VERSION for prod images != nightly
      #IMAGE_VERSION: ${{ github.ref_name }}
#      SUPPORTED_ARCH: '["amd64","arm64"]'
      SUPPORTED_ARCH: '["arm64"]'
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
