name: (level 1,2 sub) Manifest

on:
  workflow_call:
    inputs:
      MANIFEST:
        required: true
        type: string
      MANIFEST_LIST:
        required: true
        type: string
    secrets:
      DOCKER_PASSWORD:
        required: true
      DOCKER_USERNAME:
        required: true

jobs:
  manifest:
    name: Create and push manifest list
    runs-on: self-hosted
    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create and push manifest
        if: success()
        run: |
          echo "Create manifest"
          docker manifest create ${{ inputs.MANIFEST_LIST }} ${{ inputs.MANIFEST }}
          docker manifest push ${{ inputs.MANIFEST_LIST }}
          docker manifest rm ${{ inputs.MANIFEST_LIST }}