on:
  workflow_call:
    inputs:
      DOCKER_BUILD_REPO:
        required: true
        type: string
      IMAGE_BASE_NAME:
        required: true
        type: string
      ARCH:
        required: true
        type: string


jobs:
  pre_test:
    name: Pre-test
    runs-on:
      - self-hosted
      - builder
      - ${{ inputs.ARCH }}
    steps:
      - name: Read tests from image
        id: prepare
        run: |
          ID=$(docker run --rm -t -d ${{ inputs.DOCKER_BUILD_REPO }}:${{ inputs.IMAGE_BASE_NAME }}-${{ inputs.ARCH }} endless)
          docker exec $ID zsh -c 'cat /.exegol/build_pipeline_tests/all_commands.txt | grep -vE "^\s*$" | sort -u > /.exegol/build_pipeline_tests/all_commands.sorted.txt'
          line_count=$(docker exec $ID zsh -c 'wc -l /.exegol/build_pipeline_tests/all_commands.sorted.txt | cut -d " " -f 1')
          echo "$line_count test commands found!"
          docker exec $ID python3 /.exegol/build_pipeline_tests/ingest_tests.py
          docker exec $ID zsh -c 'cat /.exegol/build_pipeline_tests/tests.json'
          echo "matrix_tests=$(docker exec $ID zsh -c 'cat /.exegol/build_pipeline_tests/tests.json')" >> $GITHUB_OUTPUT
          docker stop $ID
    outputs:
      matrix_tests: ${{ steps.prepare.outputs.matrix_tests }}
#  debug:
#    name: Debug
#    runs-on:
#      - self-hosted
#      - builder
#      - ${{ inputs.ARCH }}
#    needs: pre_test
#    if: ${{ always() && needs.pre_test.result == 'success' }}
#    steps:
#      - name: Read tests
#        run: |
#          echo "${{ needs.pre_test.outputs.matrix_tests }}"
#          echo "${{ fromJson(needs.pre_test.outputs.matrix_tests) }}"
  test:
    name: Test
    needs: pre_test
    if: ${{ always() && needs.pre_test.result == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        # list of lists. Each sublist is made of up to 250 commands (max for one workflow)
        # each sublist will be iterated into in the sub_test.yml workflow
        batch_of_250: ${{ fromJson(needs.pre_test.outputs.matrix_tests) }}
    uses: ./.github/workflows/sub_test_batch.yml
    with:
      DOCKER_BUILD_REPO: ${{ inputs.DOCKER_BUILD_REPO }}
      IMAGE_BASE_NAME: ${{ inputs.IMAGE_BASE_NAME }}
      ARCH: ${{ inputs.ARCH }}
      TESTS: ${{ matrix.batch_of_250 }}