name: (level 1 sub) Manifest

on:
  workflow_call:
    inputs:
      DOCKER_PREPROD_REPO:
        required: true
        type: string
      PREPROD_MANIFEST_LIST:
        required: true
        type: string
      PROD_MANIFEST_LIST:
        required: true
        type: string
    secrets:
      DOCKER_PASSWORD:
        required: true
      DOCKER_USERNAME:
        required: true

jobs:
  manifest:
    name: Create and push manifest list
    runs-on: self-hosted
    steps:
      - name: Inspect preprod manifest
        id: inspect_manifest
        run: |
          echo "DIGESTS=$(docker manifest inspect ${{ inputs.PREPROD_MANIFEST_LIST }} | jq -r '.manifests[].digest' | while read digest; do echo ${{ inputs.DOCKER_PREPROD_REPO }}@$digest ; done | tr '\n' ' ')"
          echo "DIGESTS=$(docker manifest inspect ${{ inputs.PREPROD_MANIFEST_LIST }} | jq -r '.manifests[].digest' | while read digest; do echo ${{ inputs.DOCKER_PREPROD_REPO }}@$digest ; done | tr '\n' ' ')" >> $GITHUB_OUTPUT
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create manifest
        if: success()
        run: |
          docker manifest create ${{ inputs.PROD_MANIFEST_LIST }} ${{ steps.inspect_manifest.outputs.DIGESTS }}
      - name: Push manifest to prod
        if: success()
        run: |
          docker manifest push ${{ inputs.PROD_MANIFEST_LIST }}
      - name: Remove local manifest
        if: always()
        run: |
          docker manifest rm ${{ inputs.PROD_MANIFEST_LIST }}